### ISSUE TITLE
Feature and Review Main Pages

### ISSUE THREAD

**Issue by JKThanassi** [wrbb/WRBB-Site#17]
## Issue is about..
  - [x] a Feature Request

[Design](https://www.figma.com/file/k4SVMvJNXZ78ZJAtKfr7Nq/Website-2019?node-id=0%3A468)
(Base these off of the Article and Music Main Pages in the Figma, we're doing Feature and Review instead to mimic the current site)

# Todos

- [ ]  Create page templates for the Feature and Review Main Pages. Should look and function the same way as the regular Homepage.
- [ ] Create categories for each so that if posts are assigned to them, they will appear on the Feature or Review Main Page.
- [ ] Should be able to have their own image sliders separate from other main pages.
- [ ] Create categories that populate each main page slider with the featured images of the posts that they contain.
   - If the category has more than 5 posts, just show the first 5 in the slider
   - If it has one, show a static image of that one
   - If it has none, show a default static image
