### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by spencerlachance** [wrbb/WRBB-Site#21]
## Issue is about..
  - a Feature Request

[Design](https://www.figma.com/file/k4SVMvJNXZ78ZJAtKfr7Nq/Website-2019?node-id=0%3A1)

# Todos
- [ ] Create page template for FAQ page and design it according to the Figma.
- [ ] Use Javascript to make the answers show up when the user hovers and/or clicks on a question
- [ ] Try not to hardcode any text in the code. The user should be able to edit this page at will.
    - In order for this to work with the javascript stuff, you could create custom reusable blocks that would have the classes you need and which the user could insert into the editor: one for questions and one for answers
- [ ] Work with @spencerlachance to figure out what the questions/answers will be
