### ISSUE TITLE
Category pages

### ISSUE THREAD

**Issue by spencerlachance** [wrbb/WRBB-Site#25]
## Issue is about..
  - a Feature Request

## Design
This is not on Figma, so will have to be winged

# Todos
- [ ] `archive.php` contains the template used to display categories. Edit it so it doesn't look terrible. I would check out the category pages on the current site for inspiration. Example: http://www.wrbbradio.org/category/interview/
- [ ] For each post, display its featured image, title, date, author, and blurb w/ the first few sentences or whatever.
- [ ] Get rid of that nasty sidebar and the "Posted in" line
- [ ] Mostly, this will be an open-ended task design-wise. As long as it looks good an functions, I'll be happy.

As always, reach out to @spencerlachance with further questions
