### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by spencerlachance** [wrbb/WRBB-Site#42]
## Issue is about..
  - [ ] a Feature Request

# Todos
Style the following components on mobile/tablet:

**Category pages**
 * Could use some sprucing up on mobile, tablet looks fine
    * [x] Thumbnail images should be centered
    * [x] Add some spacing around the text

**Album Reviews, Interviews, Editorials, Show Reviews** (all use `interview.scss`)
 * [x] Fix the sidebar on tablet: Change the breakpoint at the bottom of `interview.scss` so it applies to both mobile and tablet (see bottom of `header.scss` for example of this).
 * [x] Make the post title a little smaller on mobile.

**Footer**
 * [ ] Make the email form and title look nice on mobile and tablet (or just remove it)
 * [x] Add some more space on the bottom for the playerbar on mobile

**Related articles**
 * [x] Center the RA title

**Homepage + Feature and Review Main Pages**
 * [x] Use Bootstrap col classes to make the articles 2x4 instead of 4x2 on tablet
