### ISSUE TITLE
Search results template

### ISSUE THREAD

**Issue by spencerlachance** [wrbb/WRBB-Site#44]
## Issue is about..
  - a Feature Request

# Todos

- [ ] Fix up the `search.php` file.
- [ ] Remove the sidebar
- [ ] The look of this page should be consistent with the category pages (`archive.php`) and the author pages (`author.php`)
  * Just load the `content-archive` template instead of `content-search` and that should do a bulk of the work for you
