### ISSUE TITLE
Last minute Playerbar tweaks

### ISSUE THREAD

**Issue by spencerlachance** [wrbb/WRBB-Site#67]
# Todos
- [x] Show "No DJ" or something similar when there is no show on-air
- [x] Change the cursor when you hover over the play button and volume bar
- [x] Audio starts playing if you move the volume bar when paused
- [x] Make sure the Spinitron query accurately grabs the current show
